server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React Router — все пути отдаём index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксируем аналитику
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Проксируем все REST эндпоинты backend
    location ~ ^/(salons|masters|clients|appointments|register|login|users|services-with-prices|upload|uploads)/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}